In [1]:
import pandas as pd

In [4]:
ruta = r'C:\Users\franc\OneDrive\Escritorio\Henry\Cursado Henry\PF\ML\Yelps_reviews.csv'

reviews = pd.read_csv(ruta, sep=',', encoding='utf-8')

In [18]:
reviews.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,OAhBYw8IQ6wlfw1owXWRWw,1C2lxzUo1Hyye4RFIXly3g,BVndHaLihEYbr76Z0CMEGw,5,0,0,0,"Great place for breakfast! I had the waffle, w...",2014-10-11 16:22:06
1,mO398Ed5dpv1H5ZsKc8KXw,yobeeTUBfaTBcnk26mXNuA,hKameFsaXh9g8WQbv593UA,4,0,0,0,Food was good- atmosphere/decor is like a fish...,2015-04-15 15:30:48
2,TcCcHzc3L6Aboq3DteEfZA,OuatwND396ZQxm2zK8WlUQ,jNL5KUPz2-tHUJM__ysSaw,1,1,0,0,If you want to pay for everything a la carte t...,2014-08-24 20:14:12
3,meGaFP7yxQdjyABrYDVeoQ,_jaJDV-qTBafatbObmtzpA,cg4JFJcCxRTTMmcg9O9KtA,1,0,1,0,Skip this train wreck if you are looking for d...,2018-02-11 03:11:20
4,FMFZoES5LfumuwhsZbIDlQ,4ubLHlnMFFw4JikcXr-F4w,f4PA-f1tcN1bIpZJLdFsQQ,5,3,0,0,"I must admit, I wasn't expecting much. This pl...",2017-05-26 02:32:01

In [5]:
data_test = reviews[['review_id','stars','text','date']]

In [20]:
data_test.head()

,review_id,stars,text,date
0,OAhBYw8IQ6wlfw1owXWRWw,5,"Great place for breakfast! I had the waffle, w...",2014-10-11 16:22:06
1,mO398Ed5dpv1H5ZsKc8KXw,4,Food was good- atmosphere/decor is like a fish...,2015-04-15 15:30:48
2,TcCcHzc3L6Aboq3DteEfZA,1,If you want to pay for everything a la carte t...,2014-08-24 20:14:12
3,meGaFP7yxQdjyABrYDVeoQ,1,Skip this train wreck if you are looking for d...,2018-02-11 03:11:20
4,FMFZoES5LfumuwhsZbIDlQ,5,"I must admit, I wasn't expecting much. This pl...",2017-05-26 02:32:01

In [21]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792133 entries, 0 to 792132
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   review_id  792133 non-null  object
 1   stars      792133 non-null  int64
 2   text       792133 non-null  object
 3   date       792133 non-null  object
dtypes: int64(1), object(3)
memory usage: 24.2+ MB

In [6]:
data_test = data_test.iloc[:1000]

In [7]:
data_test.to_csv('review_data_test.csv', index=False)

In [8]:
review_data_test = pd.read_csv(r'C:\Users\franc\OneDrive\Escritorio\Henry\Cursado Henry\PF\ML\review_data_test.csv')

In [9]:
review_data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review_id  1000 non-null   object
 1   stars      1000 non-null   int64
 2   text       1000 non-null   object
 3   date       1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

VAMOS A UTILIZAR EL METODO LATENT DIRICHLET ALLOCATION (LDA), LA CUAL ES UTILIZADA PARA EL ANALISIS DE TOPICOS. El algoritmo agrupa palabras que tienden a aparecer juntas en los mismos documentos, revelando los "tópicos" ocultos.

In [12]:
prueba = review_data_test['text']

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# Ejemplo de preprocesamiento y aplicación de LDA
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(prueba)

LDA_model = LatentDirichletAllocation(n_components=4, random_state=42)
LDA_model.fit(doc_term_matrix)

topics = LDA_model.components_

In [16]:
import numpy as np

# Obtener los nombres de las palabras (vocabulario)
vocab = vectorizer.get_feature_names_out()

# Número de palabras más importantes a mostrar por tema
n_top_words = 10

for topic_idx, topic in enumerate(LDA_model.components_):
    print(f"Tema {topic_idx}:")
    # Obtener las palabras más relevantes para el tema
    top_words_idx = topic.argsort()[-n_top_words:]
    top_words = [vocab[i] for i in top_words_idx]
    print(" ".join(top_words))

Tema 0:
sauce ordered order pizza best great food good place chicken
Tema 1:
order staff time cheese place like coffee food great good
Tema 2:
friendly just really like time service good great place food
Tema 3:
order menu time great food good just place like pizza

In [ ]:
# DEBERIAMOS PROBAR ELIGIENDO LAS REVIEWS DE FORMA ALEATORIA.