MODELO A DESARROLLAR: PREDICCION DE LOS MEJORES LUGARES PARA COLOCAR UN RESTARANTE. 

DATOS A USAR: UBICACION DE RESTAURANTES Y LUGARES DE INTERES.

VAMOS A INTENTAR AGREGAR UNA CARACTERISTICA A LOS RESTARUANTES, QUE SERIA SI ESTAN CERCANOS A ALGUN LUGAR DE INTERES Y SI ESO ESTA RELACIONADO CON UN AUMENTO EN EL PUNTAJE DEL RESTAURANTE.

In [1]:
import pandas as pd

In [10]:
ruta_restaruant = r'C:\Users\franc\OneDrive\Escritorio\Henry\Cursado Henry\PF\ML\restaurantes csv\restaurantes_2020.csv'
ruta_lugares_interes = r'C:\Users\franc\OneDrive\Escritorio\Henry\Cursado Henry\PF\ML\Parques_de_diversiones_Centros_comerciales csv\Parques_de_diversiones_Centros_comerciales_2020.csv'

In [11]:
restaurant = pd.read_csv(ruta_restaruant)
lugares_interes = pd.read_csv(ruta_lugares_interes)

In [19]:
restaurant.head(3)

,id_nombre,nombre,direccion,id_ciudad,ciudad,codigo_postal,latitud,longitud,puntuacion_yelp,categories,puntuacion_usuarios,anio,analisis_sentimientos
0,0002,London Heights British Pub,7701 N Nebraska Ave,RGTW,Tampa,33664,28.017764,-82.451033,3.5,"Bars, Pubs, Sports Bars, Nightlife, Restaurant...",3.1,2020,1.0
1,0010,Orderqd,"4304 S Dale Mabry Hwy, Ste 1",RGTW,Tampa,33664,27.903033,-82.505446,4.5,"Burgers, Chicken Wings, Restaurants, Chicken S...",4.6,2020,1.0
2,0013,Chulas Mexican Grill,11061 Spring Hill Dr,I0WF,Spring Hill,34610,28.461770,-82.541448,3.5,"Mexican, Restaurants",3.0,2020,1.0

In [20]:
lugares_interes.head(3)

,id_nombre,nombre,direccion,latitud,longitud,id_ciudad,ciudad,estado,pais,codigo_postal,anio
0,1,Titusville Mall,"Narvaez Drive, Titusville",28.575472,-80.802640,MU07,Mims,Florida,United States,32780,2020
1,2,Landmark Shopping Center,"North 20th Street, Hillsborough",28.068730,-82.436298,W2W7,Brandon,Florida,United States,33613,2020
2,3,LandMark Plaza,"East Fletcher Avenue, Hillsborough",28.068711,-82.437068,W2W7,Brandon,Florida,United States,33613,2020

VAMOS A COLOCAR EN UN MAPA LOS LUGARES DE RESTARUANTES Y LOS LUGARES DE INTERES PARA TENER UNA VISTA EN GENERAL DE LA DISTRIBUCION.

In [51]:
restaurant_lat_long = restaurant[['id_nombre','latitud','longitud']][restaurant['puntuacion_yelp'] > 4.5]
lugares_interes_lat_long = lugares_interes[['id_nombre','latitud','longitud']]

In [52]:
restaurant_lat_long['id_nombre'].count()

176

In [54]:
lugares_interes_lat_long['id_nombre'].count()

360

In [55]:
import folium

# Cargar los datasets
# df_restaurantes = pd.read_csv('restaurant_lat_long.csv')
# df_lugares_interes = pd.read_csv('lugares_interes_lat_long.csv')

# Crear un mapa centrado en una coordenada específica (por ejemplo, la primera de los restaurantes)
mapa = folium.Map(location=[restaurant_lat_long.iloc[0]['latitud'], restaurant_lat_long.iloc[0]['longitud']], zoom_start=12)

# Añadir los restaurantes al mapa
for index, row in restaurant_lat_long.iterrows():
    folium.Marker([row['latitud'], row['longitud']], popup=row['id_nombre'], icon=folium.Icon(color='blue')).add_to(mapa)

# Añadir los lugares de interés al mapa
for index, row in lugares_interes_lat_long.iterrows():
    folium.Marker([row['latitud'], row['longitud']], popup=row['id_nombre'], icon=folium.Icon(color='red')).add_to(mapa)

# Guardar el mapa en un archivo HTML
mapa.save('mapa_restaurantes_lugares_interes.html')

VAMOS A CREAR LA CATEGORIA PARA RESTAURANTES QUE DETERMINE SI ESTA CERCA DE UN PUNTO DE INTERES O NO. DEFINIMOS COMO CERCA DE UN RESTAURANT A: 

ESTO NOS PUEDE SERVIR PARA VER SI EXISTE RELACION ENTRE LA CERCANIA Y EL PUNTAJE.

TAMBIEN SERIA INTERESANTE CLASIFICAR A LOS RESTAURANTES SEGUN SU PUNTUACION, COMO 'REGULARES', 'BUENOS' Y 'EXCELENTES'. DEFINIMOS A LAS CATEGORIAS COMO: REGULARES - , BUENOS - , EXCELENTES - .

ESTO ME PUEDE SERVIR PARA VISUALIZAR DE FORMA GRAFICA LOS DISTINTOS PUNTOS SEGUN SU CATEGORIA Y SU CERCANIA A LOS PUNTOS DE INTERES.