In [ ]:
import pandas as pd

In [ ]:
# Habilitamos al notebook a ingresar a nuestro Drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# UNIFICAMOS JSON EN UN SOLO CSV

import os

# Ruta de la carpeta donde están los archivos JSON
carpeta = "/content/drive/MyDrive/Colab Notebooks/review-Florida"

# Crear una lista para almacenar los DataFrames
dataframes = []

# Iterar sobre los archivos JSON en la carpeta
for archivo in os.listdir(carpeta):
    if archivo.endswith(".json"):  # Asegurarse de que sea un archivo JSON
        ruta_completa = os.path.join(carpeta, archivo)
        try:
            # Leer el archivo JSON como DataFrame (formato línea por línea)
            df = pd.read_json(ruta_completa, lines=True)
            dataframes.append(df)
        except ValueError as e:
            print(f"Error al leer el archivo {archivo}: {e}")

# Concatenar todos los DataFrames
if dataframes:  # Verificar si hay DataFrames en la lista
    df_unificado = pd.concat(dataframes, ignore_index=True)

    # Exportar a un archivo CSV con escapechar
    ruta_csv = os.path.join(carpeta, "review_estado_florida.csv")
    df_unificado.to_csv(ruta_csv, index=False, escapechar="\\")  # Agregar un carácter de escape
    print(f"Archivos unificados y exportados a {ruta_csv}")
else:
    print("No se pudieron leer archivos JSON correctamente.")

Archivos unificados y exportados a /content/drive/MyDrive/Colab Notebooks/review-Florida/unificado.csv

In [ ]:
df_unificado.shape

(2550000, 8)

In [ ]:
# Abrimos el archivo creado.

review_estado_florida = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/review-Florida/review_estado_florida.csv')

In [ ]:
review_estado_florida.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.009873e+20,Quasha Jackson,1592413625176,5,NaN,NaN,"{'time': 1592425025075, 'text': 'Thanks Quasha...",0x88e5b65aaaaaaaab:0xb5b7a34b160c7c3f
1,1.121208e+20,Robert McCracken,1477961402026,3,NaN,NaN,"{'time': 1598374208890, 'text': 'Robert thank ...",0x88e5b65aaaaaaaab:0xb5b7a34b160c7c3f
2,1.030253e+20,Tau B,1545107865599,5,NaN,NaN,"{'time': 1572716768704, 'text': 'Thank you for...",0x88e5b65aaaaaaaab:0xb5b7a34b160c7c3f
3,1.148148e+20,amanda miller,1532716007707,5,NaN,NaN,"{'time': 1572717861138, 'text': 'Thanks for th...",0x88e5b65aaaaaaaab:0xb5b7a34b160c7c3f
4,1.090946e+20,Courtney Coats,1545108790970,5,NaN,NaN,"{'time': 1572716704243, 'text': 'Thank you for...",0x88e5b65aaaaaaaab:0xb5b7a34b160c7c3f

In [ ]:
# Hacemos limpieza de datos. Primero eliminamos la columna pics por no contener informacion relevante.

review_estado_florida.drop('pics', axis=1, inplace=True)

In [ ]:
# Eliminamos la columna time por no contener informacion relevante.

review_estado_florida.drop('time', axis=1, inplace=True)

In [ ]:
# Eliminamos todas las filas vacias de la columna text.

review_estado_florida.dropna(subset=['text'], inplace=True)

In [ ]:
review_estado_florida.shape

(1573083, 6)

In [ ]:
review_estado_florida.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1573083 entries, 8 to 2549999
Data columns (total 6 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   user_id  1573083 non-null  float64
 1   name     1573074 non-null  object
 2   rating   1573083 non-null  int64
 3   text     1573083 non-null  object
 4   resp     283449 non-null   object
 5   gmap_id  1573083 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 84.0+ MB

In [ ]:
review_estado_florida.head()

,user_id,name,rating,text,resp,gmap_id
8,1.167469e+20,Vanessa Spivack,5,Fantastic place to go. My kids won’t go anywh...,NaN,0x88d91b4d6ad4bfd1:0x1c708e8773ae009f
9,1.069119e+20,Paola Benitez,1,When there with my 2 daughters and the place i...,NaN,0x88d91b4d6ad4bfd1:0x1c708e8773ae009f
10,1.050457e+20,Aurora Steekley,5,Happy environment and fun haircut salon for th...,NaN,0x88d91b4d6ad4bfd1:0x1c708e8773ae009f
11,1.087262e+20,Anthony D Colon,1,Been sitting here for over an hour and my son ...,NaN,0x88d91b4d6ad4bfd1:0x1c708e8773ae009f
12,1.149723e+20,Ollys Oropeza,5,Very good place for kids...,"{'time': 1526759157410, 'text': 'Thank you so ...",0x88d91b4d6ad4bfd1:0x1c708e8773ae009f

In [ ]:
# A tener en cuenta que este archivo contiene reviews para TODOS los tipos de negocios, no solamente de restaurantes.

In [ ]:
# Guardamos el archivo nuevamente.

review_estado_florida.to_csv('/content/drive/MyDrive/Colab Notebooks/review-Florida/reviews_florida.csv', index=False)